version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "phpunit-action"
      - dependency-name: "create-issue"
      - dependency-name: "auto-semver"
